# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: plex
  annotations:
    external-dns.alpha.kubernetes.io/target: "10.0.0.216"
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`plex.ajphome.com`)
    kind: Rule
    services:
    - name: plex
      port: 32400
  tls:
    secretName: plex-tls
