# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: ConfigMap
metadata:
  name: openssh-server-custom-scripts
data:
  fetch-ssh-ca.sh: |
    #!/bin/bash
    set -e
    wget -qO /config/ssh_ca_key.pub http://vault.ajphome.com/v1/ssh-ca/public_key
    if ! grep -q "TrustedUserCAKeys" /config/sshd_config; then
      echo "TrustedUserCAKeys /config/ssh_ca_key.pub" >> /config/sshd/sshd_config
    fi
