# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: openssh-server
        image: linuxserver/openssh-server
        ports:
        - containerPort: 2222
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: PASSWORD_ACCESS
          value: "false"
        - name: SUDO_ACCESS
          value: "false"
        - name: USER_NAME
          value: "jellyfin"
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: openssh-server-creds
              key: authorized_key
        volumeMounts:
        - name: config
          mountPath: /config
        - name: sshd-config
          mountPath: /config/sshd/sshd_config.d
        - name: home
          mountPath: /home
        - name: media
          mountPath: /data
      volumes:
      - name: config
        emptyDir: {}
      - name: sshd-config
        configMap:
          name: openssh-server-sshd-config
      - name: home
        emptyDir: {}
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-jellyfin-media
