# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebrowser
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./filebrowser
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-storage
    namespace: flux-system
  targetNamespace: jellyfin
  dependsOn:
    - name: cert-manager
    - name: jellyfin
