# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- cert-manager.helmrelease.yaml
- cert-manager.kustomization.yaml
- device-plugin-node-prep.kustomization.yaml
- device-plugin-operator.helmrelease.yaml
- external-dns.helmrepository.yaml
- external-dns.helmrelease.yaml
- gpu-device-plugin.helmrelease.yaml
- homelab-storage.gitrepository.yaml
- intel.helmrepository.yaml
- jellyfin.helmrepository.yaml
- jellyfin.helmrelease.yaml
- jellyfin.kustomization.yaml
- jetstack.helmrepository.yaml
- metallb.helmrelease.yaml
- metallb.helmrepository.yaml
- metallb.kustomization.yaml
- nfd.helmrelease.yaml
- nfd.helmrepository.yaml
- rbac.kustomization.yaml
- topolvm.helmrepository.yaml
- topolvm.helmrelease.yaml
- traefik.helmrepository.yaml
- traefik.helmrelease.yaml
