# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
spec:
  interval: 5m0s
  path: ./plex
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-storage
  targetNamespace: plex
  dependsOn:
    - name: cert-manager
    - name: traefik
